[package]
name = "attractor"
version = "0.1.0"
authors = ["Harry <hlbarber93@gmail.com>"]

[dependencies]
futures = "*"
tokio = "*"
rocksdb = "*"
libc = "*"
bytes = "*"
dirs = "*"
memcache = "*"
indradb = "*"
blake2 = "*"
hex-literal = "*"

[dev-dependencies]
rand = "*"